# Generated by Django 4.2.3 on 2023-07-24 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matrimonial", "0002_caste_father_hobby_religion_sect_profile_caste_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="Sect",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profiles",
                to="matrimonial.sect",
            ),
        ),
    ]
